# Generated by Django 3.1.4 on 2021-03-19 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(default='', max_length=50)),
                ('zone', models.IntegerField(default=-1)),
                ('division', models.IntegerField(default=-1)),
                ('connection', models.CharField(default='', max_length=100)),
                ('interchange', models.CharField(default='', max_length=100)),
                ('station', models.CharField(default='', max_length=100)),
                ('station_code', models.CharField(default='', max_length=100)),
                ('distance_in_km', models.FloatField(default=0.0)),
                ('layout', models.CharField(default='', max_length=100)),
                ('parking_contract_available', models.CharField(default='', max_length=10)),
                ('space_available_no_contract', models.CharField(default='', max_length=10)),
                ('space_not_available', models.CharField(default='', max_length=10)),
                ('insertedAt', models.DateTimeField(auto_now=True, db_column='inserted_at')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'rail_infos',
            },
        ),
    ]
